### ISSUE TITLE
Unused admin client

### ISSUE THREAD

**Issue by cotedm** [Dabz/ccloudexporter#1]
I noticed that the admin client is failing to connect. It appears unused (and should be unnecessary) so I recommend removing references to it: https://github.com/Dabz/ccloudexporter/blob/master/cmd/ccloudexporter/ccloudexporter.go#L30-L40

**Comment by Dabz** [comment]
Now that I increased this limit, all topics are properly fetched (thanks to the retained_bytes metrics ;)). I removed the dependency of the admin client in #8
