### ISSUE TITLE
Support exporting for multiple clusters

### ISSUE THREAD

**Issue by cotedm** [Dabz/ccloudexporter#24]
It would be useful to be able to support exporting for multiple clusters. The Metrics API can do this  by using an OR:

`    "filter": {
        "filters": [
            {   
                "field": "metric.label.cluster_id",
                "op": "EQ",
                "value": "lkc-XXXX1"
            },  
            {   
                "field": "metric.label.cluster_id",
                "op": "EQ",
                "value": "lkc-XXXX2"
            }   
        ],  
        "op": "OR"
    },`

Results from the query can also be grouped by both the cluster id and the topic name to avoid collisions of topic names across clusters:

`    "group_by": [
        "metric.label.cluster_id",
        "metric.label.topic"
    ],`

Finally, you can also use the [new `GROUPED` format by passing in the `format` parameter](https://api.telemetry.confluent.cloud/docs#/paths/~1v1~1metrics~1{dataset}~1query/post) to make the grouping more explicit if it is helpful.

**Comment by sirianni** [comment]
+1

This will become necessary to adhere to API rate limits for environments with many Kafka clusters.

**Comment by Dabz** [comment]
Got it! I will move this issue higher in my in-memory backlog and implement it in my next major iteration. The more I think about it, the more I think ccloudexporter need a configuration file :thinking:
