### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by alonisser** [Dabz/ccloudexporter#27]
In order to incorporate this as part of a production monitoring solution I'm looking for a "health" endpoint that would fail if this app is down, is there such an endpoint which isn't the metrics endpoint that seems to be hitting the cluster everytime? 

Thanks a lot for this project

**Comment by Dabz** [comment]
There is no "health" http endpoint currently, only /metrics is exposed: https://github.com/Dabz/ccloudexporter/blob/master/cmd/ccloudexporter/ccloudexporter.go#L24
Scrapping "/metrics" could do the job, but it would create a few issues:

- Every time you request /metrics, a few queries are sent to the Metrics API, thus it would drastically increase the number of queries per seconds
- /metrics would reply even if queries would fail on Metrics API

I am assuming that you are discussing about "health" endpoint to configure some kind of liveliness check. At the moment, ensuring that the process is running should be quite sufficient, if you want to ensure that the exporter is working properly, creating alert if there are missing/absent point should be the way to go.

With the previous explanation, do you still think it would make sense to provide a "health" endpoint?

**Comment by alonisser** [comment]
Yes, because that's what I'm trying to ensure tha the process is running and not "stuck" in unresponsive mode. but maybe that isn't an issue here and isn't a real problem. 
Thanks for the response

**Comment by Dabz** [comment]
> Yes, because that's what I'm trying to ensure tha the process is running and not "stuck" in unresponsive mode. but maybe that isn't an issue here and isn't a real problem.

If you want to ensure that the process is running properly, you should probably configure an alert
