### ISSUE TITLE
Question: is there a way to provide cluster id as an environment variable

### ISSUE THREAD

**Issue by alonisser** [Dabz/ccloudexporter#28]
For easier integration with k8s secrets?

Thanks for this project!

**Comment by Dabz** [comment]
At the moment, there is no way to provide the cluster id as an environment variable. It can only be provided with the command line.
I am planning to do some rework on the option to add a few new ones soon, I will keep this point in mind.

**Comment by alonisser** [comment]
Thanks!

**Comment by Dabz** [comment]
As part of #30, you can not specify the environment variable CCLOUD_CLUSTER.
If `-cluster` is not specified, the environment variable CCLOUD_CLUSTER will be used.

**Comment by Dabz** [comment]
Implemented as part of #30
