### ISSUE TITLE
Used attributes endpoint for topic list

### ISSUE THREAD

**Issue by cotedm** [Dabz/ccloudexporter#3]
Recommend using the 'attributes' endpoint to get the topic list to avoid any future dependency on the admin client: https://github.com/Dabz/ccloudexporter/blob/master/cmd/internal/scrapper/scrapper.go#L38-L54

https://api.telemetry.confluent.cloud/v1/metrics/{dataset}/attributes

**Comment by Dabz** [comment]
That would indeed be much better! I was not aware of this endpoint :sweat_smile: 

Looking at the documentation: https://docs.confluent.io/current/cloud/metrics-api.html, this endpoint does not seem to be documented (or maybe I am missing another page?), do you want me to open a ticket somewhere to request a DOC improvement?

**Comment by Dabz** [comment]
After increasing the limit of my query, all topics are discovered properly. It seems to be due as the retained metrics is returning all topic by default. As the discovering is working properly now, I am not sure that calling the attributes endpoint is strictly required :thinking:

**Comment by cotedm** [comment]
Probably not required, but would be helpful in specifying your limit I guess.

**Comment by Dabz** [comment]
The admin client has been removed. `ccloud_metric_retained_bytes` is returning a point for each topic in each query, this is sufficient for our dashboarding and monitoring need. I am closing this issue as I can not think of a reason to let it open.
