### ISSUE TITLE
Better indicate deprecation of username/password authentication

### ISSUE THREAD

**Issue by sirianni** [Dabz/ccloudexporter#39]
Username/password authentication to the Metrics API was only supported in the preview phase.  For GA release, only API key/secret authentication is officially supported.

* Rename `CCLOUD_USER` and `CCLOUD_PASSSWORD` environment variables to `CCLOUD_APIKEY` and `CCLOUD_APISECRET` respectively
  * The legacy environment variables may still need to be supported to maintain backwards compatibility
* Update the README accordingly

**Comment by Dabz** [comment]
That's quite an important change. I will do the change & the documentation (with a big disclaimer in the README) ASAP.
I assume that username/password authentication will no longer be supported at some point, right?

**Comment by sirianni** [comment]
> I assume that username/password authentication will no longer be supported at some point, right?

Correct.  We are looking to sunset this later in Q3.
