### ISSUE TITLE
Please add successful authentications 

### ISSUE THREAD

**Issue by l0n3r4n83r** [Dabz/ccloudexporter#42]
The API now also exposes numbers for successful authentications

**Comment by Dabz** [comment]
I will consider adding this metric in the default configuration.
In the meantime, if you would like to gather this metric, you could easily add it in the configuration file: https://github.com/Dabz/ccloudexporter/blob/master/config/config.simple.yaml#L13

**Comment by Dabz** [comment]
@l0n3r4n83r , just to let you know, I added the successful authentications as a default metric (#45) ;) 
I am closing this issue for now.
