### ISSUE TITLE
Query intervals should be aligned to minute boundaries

### ISSUE THREAD

**Issue by sirianni** [Dabz/ccloudexporter#46]
The query interval `timeFrom` is taken by applying the configured delay to `time.Now()`
https://github.com/Dabz/ccloudexporter/blob/77195baebee292593d6a56255a971e5c415beb41/cmd/internal/collector/query.go#L72

Instead, the start time should be `time.Now()` with the seconds truncated (i.e. rounded down to the nearest minute).  Since the Metrics API only stores data at minutely granularity, using `time.Now()` is effectively rounding **up** to the next minute, which makes the effective delay less than the configured delay.

For example:
* Delay (configured): `120 seconds`
* Current time: `00:10:05`
* Query interval (actual): `00:08:05 / PT1M` 
* Query interval (effective): `00:09:00 / PT1M` (only metrics with timestamp `00:09:00` will be matched)
* Delay (effective): `65 seconds` (00:10:05 - 00:09:00)

**Comment by Dabz** [comment]
Good catch, that explains a few behaviors :/ 
Let me do the PR, it should be pretty straightforward.

**Comment by Dabz** [comment]
#47 truncate the seconds in the interval. It seems to make the delay effective: at 10:27 with a 2 minutes delay, I got the point from 10:25.
