### ISSUE TITLE
Use descriptors endpoint to get available metrics

### ISSUE THREAD

**Issue by cotedm** [Dabz/ccloudexporter#5]
Right now the list of metrics is hardcoded:
https://github.com/Dabz/ccloudexporter/blob/master/cmd/internal/scrapper/query.go#L71-L73

I recommend using the descriptors endpoint https://api.telemetry.confluent.cloud/v1/metrics/{dataset}/descriptors

An example on getting the available metrics here:
https://docs.confluent.io/current/cloud/metrics-api.html#list-the-available-metrics

**Comment by Dabz** [comment]
Done as part of #7
