### ISSUE TITLE
Metrics using Docker / Kubernetes

### ISSUE THREAD

**Issue by andrejusm** [Dabz/ccloudexporter#56]
Hello. 
Is it possible somehow to pass config with other **metrics** or just change the **metrics** we export from Confluent, when using Docker or Kubernetes?
Thank you in advance.

**Comment by Dabz** [comment]
Hi @andrejusm ! 

You can specify a configuration with new/other metrics when using Docker or Kubernetes.
Internally, the exporter will invoke the descriptor endpoint to validate your metrics https://api.telemetry.confluent.cloud/v1/metrics/cloud/descriptors, but there is no restriction on the metrics to use.

If you specify a metric that is not exposed, you should get a warning message: https://github.com/Dabz/ccloudexporter/blob/multiple_clusters/cmd/internal/collector/collector.go#L187-L189
