### ISSUE TITLE
Consider crashing if a 403 response is returned

### ISSUE THREAD

**Issue by cotedm** [Dabz/ccloudexporter#71]
It's easy to forget you have a `ccloudexporter` instance running against a cluster that has been torn down. This results in spamming 403 errors until someone notices. Since 403 errors are usually permanent failures that require user intervention to fix, consider crashing the `ccloudexporter` to fail fast if one is returned.

**Comment by Dabz** [comment]
Let me close this issue as this has been implemented as part of #93
