### ISSUE TITLE
timeout issue with docker compose

### ISSUE THREAD

**Issue by SujathaVenkat** [Dabz/ccloudexporter#90]
ccloud_exporter container logs below,
```
{
  "error": "Get \"https://api.telemetry.confluent.cloud/v2/metrics/cloud/descriptors/resources\": dial tcp: lookup api.telemetry.confluent.cloud on 127.0.0.11:53: read udp 127.0.0.1:57113-\u003e127.0.0.11:53: i/o timeout",
  "level": "fatal",
  "msg": "HTTP query for the descriptor endpoint failed",
  "time": "2021-09-21T14:12:54Z"
}

```
I tried to increase the timeout to 120 seconds as provided in README.md but no luck.
```flag.IntVar(&Context.HTTPTimeout, "timeout", 120, "Timeout, in second, to use for all REST call with the Metric API")```

Thanks in advance!

**Comment by Dabz** [comment]
Hi @SujathaVenkat , looking at the log, it seems that the DNS lookup failed: `dial tcp: lookup api.telemetry.confluent.cloud on 127.0.0.11:53: read udp 127.0.0.1:57113-\u003e127.0.0.11:53: i/o timeout"`

There is probably something in your network configuration and the process can not access the DNS server.
